travis:
  secure:
    BINSTAR_TOKEN: ejLDSacQXDovNKsiJJ7Cj+c4qWQpddjJZYPrEoSYttdie19iRIm5VODoHquuG7nmae7tRnzIgLaKLGweYHLS9kUg2GY/M0KLqLURR5Sks+pQSEO9ZxXcRsCeYnsxIkdfRhtCA/D+yWX1xK3g3wylBr/6Ujk2VclxIlRcqHswpXpImctaJvghADlkkmJbHhU5rFbnSzLWjL5lSIijSyqRwVYpaB+rw+mqHQwO3bwAenla7Fd5mYgR695rsXlYgDd1G6Do7djfWnwEH073TGaTV6TWxbJ2hu+36MsZEk9bm3QR+zYgcPXDaw5tQMNaf+hzTNhnRJdx9kMAGOR8s9NdZ5ob6PoI0Kx5uYtaxfmn9J6c91QN8Z1UMEYHptb7rp+XtnIZbEWnKmuLnekJfpqCVBxiJlGlBKgbXRi4N2Y+sEGVh2zi9MIc+HPOWdQTb17tEryAe9t4ggkkU4PbbPGlTfcq9R99zqocTTeyRPWtzduwU0DtmueKDEAASZ1M4K0psuPIACO689XaFiO9wnmw/6Ktsv9GWHICmgnBbUwgPERpe0BA0w00OGIQtr4q2+qOFWhcSLVQk5x6UcSpqkLIKc4yotQWVJs21hR/ows4AhBW/kuypOaOHAnELlM0XihFvoKfhDyCogcupIG6SP0gjtYTYxhw26wMdggt9hXZW8M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
