travis:
  secure:
    BINSTAR_TOKEN: ghGBIqPW3pXTlfPgTxoHu+Vo2pkD+UcZb/yBYFhlJxC3wqwq7JYs98HW8OONzUrWFE8Lk7gCHA5MbdjXN8CDX5jH8vx2tZKnSTvFlon4Sab3NtQj4u0CHZJ5VvqvTOhhxAIoATbYMxIRj/vTtAiTxKpULRSHkkOUR/3uhisSfwCB0pifBOduFXdibLsidMwCvKL1WuD2Houot1dWYLbhc59rXoFjJqZo3rQdmiLbBBdB2eAmzXTfiJVc7C4t8bLAkW6WVvjaBlauHXpeZcpGqDCsPV5QHQHz+YACL6zjmtZ5FtRzU4v0Q4+zIvJa7LF2GhVR6b2jfm2K0zgenMos3FHXhZaDuLA0AjGoIyBcmXph6ASTt6TX+7qm5R1v40F2VNwA4BlNJ0aQXKkTnpnPqUl7IxRt/Qy04+SlHhihkFmIlUTFvxTpFAh74CEa01Oi+UsXDDLrAvhK7XpXcnYZWsbv+9xa9q7oepqB5XjV42H+dn9+rWTjXGguIqnvv/TfAaZVYOLDHDUNemuFSgc/unUGXFQrBG4jpJYWhcn/YybHlEg+5LeT1I26vje0HPfYVxxSXAkRdgSzDa/plUtjt25geEp1kGug9YFL94mXdLuZD/4J84h/RJS1nWsHTcQECXJAyRI2sSobEsxxPA5tKnrKCth01O/xCjreLXuRswM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
